### ISSUE TITLE
No clarity - how is an array resulting from Search Action processed?

### ISSUE THREAD

**Issue by vshabat** [zapier/visual-builder#105]
https://platform.zapier.com/docs/search-create

This says "Searches return an array of objects", but it's not clear what happens to that array later. Later it says "search actions find the first matching result". Does it mean that only the first entry of the array is passed on to the later steps and the rest of the array is discarded?

I googled a variety of hints that it should work differently, that each element of the array will be processed:
https://johnathon.blog/three-tips-for-testing-and-debugging-javascript-in-zapier-code-actions/ ("...when the zap actually runs, the full array will be processed."). This is about Code steps though, not a Search Action in a custom integration.

https://html.developreference.com/article/13816144/Loop+through+Zapier+webhook+result
("Zapier can loop through actions up to 25 times"). This is about Webhooks, also not about a Search Action in a custom integration.

https://stackoverflow.com/questions/44902165/loop-through-zapier-webhook-result
("Zapier can loop through actions up to 25 times")

I am trying to make an integration which will get all contacts associated to a lead. It's not clear if I am correct in expecting this to work. https://community.zapier.com/developer-discussion-13/processing-an-array-of-contacts-from-a-single-crm-lead-1400

**Comment by matthewheath** [comment]
> Does it mean that only the first entry of the array is passed on to the later steps and the rest of the array is discarded?

Yes, only the first item in the array is returned and used. The rest are discarded.

This repository isn't actively monitored — in the future I recommend using [the contact form](https://zapier.com/app/contact-us) and selecting **Developing an app on the Zapier platform** which will get you faster support (I used to work on that team 🙂).

**Comment by vshabat** [comment]
Hey @matthewheath - thanks! 

I thought so, and found a workaround: https://community.zapier.com/developer-discussion-13/processing-an-array-of-contacts-from-a-single-crm-lead-1400,
