### ISSUE TITLE
Your doc lacks informations about OAuth2

### ISSUE THREAD

**Issue by nathgilson** [zapier/visual-builder#107]
We learn nothing with your doc regarding the OAuth2 integretion (https://platform.zapier.com/docs/oauth?from_url=https%3A%2F%2Fzapier.com%2Fapp%2Fdeveloper%2Fapp%2F97559%2Fversion%2F1.0.0#authorization). What is the State parameter? How to deal with the cors policy? When to redirect the request and how?

**Comment by xavdid** [comment]
Your rude issue title is not appreciated nor accepted here. 

We'd be happy to help you get started with OAuth, but not until you're renamed your issue to something civil and descriptive.

**Comment by nathgilson** [comment]
@xavdid I found my way through the OAuth complexity despite the lack of documentation and I wrote a medium for the nexts who want to make an integration using firebase: https://medium.com/@nathangilson/how-to-add-oauth-v2-to-a-zapier-integration-with-firebase-6fba2a12cd54 - can you check if there is any security issues?

**Comment by zapzap** [comment]
yep, seems reasonable.
