### ISSUE TITLE
Output From Dynamic Field Documentation Issue

### ISSUE THREAD

**Issue by nmallare** [zapier/visual-builder#109]
**Link to documentation with issue**

https://platform.zapier.com/docs/input-designer#how-to-add-dynamic-and-custom-fields

**Describe the content issue**

I'm trying to take a dynamic field and create a dropdown from an API call. This view mentions a key/value relationship, but the learn more (above) doesn't really talk about how to formulate an array that can be used in a dropdown.

![image](https://user-images.githubusercontent.com/8125400/81618992-3621d180-93ae-11ea-895e-2f97552b9879.png)

**What could be improved?**

I was digging around online and found a LOT of talk about the zapier-cli library. So, using some of those examples, I came up with the following format:
```
return {
  key: '{key-value}',
  required: true,
  choices: contentTypes, // Array of [id] => label
};
```
However, this provides an out of below (which isn't ideal). So, I'm still really not sure what this return object should be defined to make it not now have the "id" listed below the name.

**Screenshots**

![image](https://user-images.githubusercontent.com/8125400/81619227-b9dbbe00-93ae-11ea-9a8a-529387257a4d.png)

**Additional context**

**Comment by matthewheath** [comment]
That highlighted grey attribute will always be shown, there's no way to hide it. At best, you could change the value being provided there to something else but in most cases that won't make sense. This is because the default value shown is usually an ID, and that's usually used by your API to operate on the chosen selected value from the dynamic dropdown.

**Comment by xavdid** [comment]
Matthew is correct - I believe the value is always shown if there's a label. There are actually 3 options for dropdowns depending on if the order matters and if you need a label. They're described here: https://github.com/zapier/zapier-platform/blob/master/packages/schema/docs/build/schema.md#fieldchoicesschema

I can get those added to these docs though!
