### ISSUE TITLE
Version depreciation - how do the users get notified about the deprecation? What prompts them to upgrade?

### ISSUE THREAD

**Issue by max-bassin** [zapier/visual-builder#120]
Hi, 
I'm referring to this doc:
https://platform.zapier.com/docs/versions#deprecate-an-older-version-of-your-integration

We have a breaking change version that we want our users to switch to. From what I understood from the doc, I would need to depricate the old version and promote the new one. The one piece that I'm missing is how the users of the old version are getting notified about the dedication, and how are they prompted to switch to the new version?

**Comment by xavdid** [comment]
Hey @max-bassin, sorry for the slow reply here. 

The modal once you submit it looks like this:

![](https://cdn.zappy.app/298bb9aad82a42c7596fe68f1ffa5c46.png)

The email users get looks like this:

![](https://cdn.zappy.app/9d616ae7530b67349b21e936bdcdb4d4.png)
