### ISSUE TITLE
How can I remove the "custom" for select?

### ISSUE THREAD

**Issue by zl939144892** [zapier/visual-builder#123]
It has caused many problems in our system. We need users only can choose an option in us to provide.
By the way, we use `zapier-platform-cli` to build.
![image](https://user-images.githubusercontent.com/18364560/88255427-fa2eb500-ccea-11ea-896e-28f4570320de.png)

**Comment by xavdid** [comment]
@zl939144892 It's not possible to remove that tab - users may want to map values from previous steps. 

Instead, you can have application logic to validate the input that throws an error if they try to provide an invalid value.
