### ISSUE TITLE
Is it possible to capture and use Action output in another Action?

### ISSUE THREAD

**Issue by jbuchmann-coosto** [zapier/visual-builder#125]
I didn't see it documented anywhere, but I noticed that Actions can have output (Data Out in the interface). Sometimes this is useful data, such as the ID of a newly-published social media post that I would like to send back to my system in a second Action. Is it possible to capture and use this output data?

**Comment by xavdid** [comment]
@jbuchmann-coosto 

> Actions can have output

Yes! anything returned from the `perform` function of an action can be picked up by any subsequent action. All you need to do return that data from the first action.
