### ISSUE TITLE
Dead API Key links on Visual Builder Auth page

### ISSUE THREAD

**Issue by kgodtfredsen** [zapier/visual-builder#13]
**Link to documentation with issue**

https://zapier.github.io/visual-builder/docs/auth

**Describe the content issue**

API Key and → Add API Key Auth to your Zapier Integration Links 404:

API Key
API key authentication lets users enter a custom API key from your app, and can optionally request additional info such as a domain. Users will need to locate an API key from your app, then enter it in the Zapier authentication form. Zapier will then pass the API key, along with any additional authentication details needed, to authenticate each API call.

→ Add API Key Auth to your Zapier Integration

https://zappy.zapier.com/DD05B76A-9CC5-4DA9-95AA-BBEA90AB1639.png

**Comment by maguay** [comment]
@kgodtfredsen Thank you, just got that fixed!
