### ISSUE TITLE
Zapier has No Documentation re required Partner API Documentation

### ISSUE THREAD

**Issue by pdogbc** [zapier/visual-builder#156]
We would like to publish our integration but when we click Publish it says we need a URL for API Documentation. It would be nice if you documented what this could look like. And give a template or examples.

When we try read the instructions your page [https://platform.zapier.com/partners/document-support](https://platform.zapier.com/partners/document-support) says "Coming Soon"... so we are being asked for this but Zapier doesn't publish any examples or criteria of what you need.

Suggestion: pls document this page so we can provide the documentation requested.

**Comment by xavdid** [comment]
@pdogbc sorry for the confusion here. That doc page definitely shouldn't be a placeholder still!

In the meantime, that url for your API docs can be literally anything that teaches developers how to use your API. There's no rules about it, we just like to have it as a reference for troubleshooting purposes. You can reference the following examples, if you'd like:

* Stripe: https://stripe.com/docs/api
* Steam: https://developer.valvesoftware.com/wiki/Steam_Web_API

If you don't have any public-facing API docs, you can also just link to your homepage.

**Comment by pdogbc** [comment]
Hi Dave.

Ok. We have no public API documentation so we documented a complete zap
creation with screenshots and put it up on our site.

Thanks.

**Comment by xavdid** [comment]
Sounds perfect!
