### ISSUE TITLE
Instagram (3rd party) Authentication

### ISSUE THREAD

**Issue by electronbabies** [zapier/visual-builder#168]
I've looked through documentation and can't exactly find what I'm looking for.  We have a zap that we manually setup that looks at an RSS feed that posts to Instagram, which works just fine.  What we want to do is to automatically set a zap up for each of our users which means a dynamic RSS URL and more importantly, the user needs to be able to authenticate with Instagram in the zap.  Is this possible?  If so can you point me in the right direction?

The way I see it is that every user will have their own zap in our account.  We do not want them to have to create their own Zapier accounts.  We want to handle the costs and make it as seemless as possible.

I appreciate you taking the time to read this.

Gary

**Comment by scottconrad** [comment]
I have the same issue for a client. We're not trying to hide we're using zapier, we're just trying to make the process seamless.

**Comment by xavdid** [comment]
Great questions! 

At this time, all Zapier users need their own Zapier account. If you've got feedback or suggestions about that, I recommend getting in touch (https://zapier.com/contact) and voicing said suggestion - our support team collects all that feedback and it helps us make product decisions. 

In the meantime, I'd suggest a shared zap: https://zapier.com/blog/updates/2271/introducing-shareable-zaps

Your users will be able to quickly set up this common zap, but it _will_ be on their own accounts. 

We also offer some setup options via the [Partner API](https://platform.zapier.com/partner_api/endpoints), but that won't accomplish what you're asking for here.

Sorry I don't have better news, but thank you for your interest!
