### ISSUE TITLE
How to add custom logo to my App using the CLI?

### ISSUE THREAD

**Issue by yanirclsr** [zapier/visual-builder#17]
I cannot find instructions anywhere.
In the editor it's very simple but none of the examples on your GitHub repo shows how to configure custom App Icon in the CLI code.
Is it a configuration in the package.json file?

**Comment by maguay** [comment]
@yanirclsr Thanks for pointing that out, and sorry we didn't have it covered before.

To add your app's logo (and set other details including your app's category), you can edit it from Zapier's online developer platform at https://zapier.com/app/developer/. First make sure you have pushed your integration to Zapier. Then, in the online view, select the app you built from the CLI, then click the gear icon beside its temporary logo and name. There you can upload your app's logo file and set any other integration details.

Here's a new tutorial on that: https://platform.zapier.com/cli_tutorials/cli-branding

Let us know if you need anything else!
