### ISSUE TITLE
Triggers documentation has a placeholder (not well-written or done sentence)

### ISSUE THREAD

**Issue by semenmiroshnichenko** [zapier/visual-builder#18]
**Link to documentation with issue**

https://platform.zapier.com/docs/triggers

**Describe the content issue**

It seems you want to add something about custom code but did not get it yet.

**What could be improved?**

Rewrite a placeholder "_Use custom code to _" with a real content.

**Screenshots**

https://i.imgur.com/AS4jWSQ.png

**Comment by maguay** [comment]
@semenmiroshnichenko Thanks for pointing that out! Just got it fixed.
