### ISSUE TITLE
integration documentation

### ISSUE THREAD

**Issue by artemu78** [zapier/visual-builder#19]
hey guys 
is there any docs explaining how my app should answer for zapier integration request (using api scheme)

**Comment by maguay** [comment]
@artemu78 Are you looking for details on the response bundle after connecting an account to Zapier with an API key?

If so, first check our API Key authentication details here: https://platform.zapier.com/docs/apikey. Or, for Zapier's Platform CLI, check our authentication docs (see the Basic and Custom sections: https://platform.zapier.com/cli_docs/docs#authentication) and a sample custom auth app (https://github.com/zapier/zapier-platform-example-app-custom-auth).

For either, though, Zapier does not actually have an API call or expected response from your app. Instead, you add a test API call, typically to a `/me` or `/user` API endpoint that returns data about the user with that API key as a single JSON formatted object. Zapier then includes that data in the `inputData` bundle that you can reference in the integration's account connection label: https://platform.zapier.com/docs/advanced#zapier-data-bundles.

If you need more help, feel free to reach out to our support team at contact@zapier.com, or join Zapier's Platform Slack group: https://join.slack.com/t/zapier-platform/shared_invite/enQtNTg1MjM5NjMzNTI3LWVhZjk3NjFlNWFiMTBmMDExMzI5NDZiZmFiOTJjYmI3NmY2MzEwZDUxNzQ3MTliMTM5N2M3NGM2MmQ2Y2VkODE

**Comment by artemu78** [comment]
Thank you buddy. Thats what i really nead.
