### ISSUE TITLE
WYSIWYG Icons Missing _Content Security Policy

### ISSUE THREAD

**Issue by nicolemichellethomas** [zapier/visual-builder#194]
**Describe the bug**

When trying to respond to a bug/feature request in the developer platform, the icons on the WYSIWIG do not display. 

**To Reproduce**

List steps to reproduce the behavior:

1. Go to the 'Bugs & Feature Requests' page in visual builder
2. Click on any open Bug or Feature Request
3. Scroll down to 'Write a new Comment to Zapier Platform Support'
4. See that in the available WYSIWIG Editor, none of the icons appear

**Expected behavior**

**Screenshots**

[Screenshot of the WYSIWYG without icons](https://cdn.zappy.app/bc21901ff1633fff3950ab9b6dd6765e.png)
[Screenshot of the console errors](https://cdn.zappy.app/0c49a0fb572d993bdc67a40b789e6513.png)

**Browser Info**

 - OS: macOS Big Sur
 - Chrome 89.0.4389.90 AND Safari 14.0.3

**Comment by zapzap** [comment]
This issue has been copied into our private issue tracker  (as [PDE-2141](https://zapierorg.atlassian.net/browse/PDE-2141)). Thanks for the report! We'll update this as we learn more.

**Comment by xavdid** [comment]
@nicolemichellethomas thanks for the report! I'll get that fixed shortly.

**Comment by xavdid** [comment]
This is fixed in production now, thank you!

![](https://cdn.zappy.app/71131e0c9fcc9097730033f86d6dfe7b.png)
