### ISSUE TITLE
Zapier 101 YouTube Playlist redirecting to deprecated playlist

### ISSUE THREAD

**Issue by justin-lee-zapier** [zapier/visual-builder#201]
**Link to documentation with issue**

https://zapier.com/developer/documentation/v2/partner-program-tips/

**Describe the content issue**

The Zapier 101 link in tip section 1 leads to a what I imagine to be and older URL to the Zapier 101 playlist.

**What could be improved?**

I believe this should be the updated link: https://www.youtube.com/playlist?list=PLqzJRGwum4KO2ISMYKmK0Ci7hm_508NfO

**Screenshots**

![](https://cdn.zappy.app/a9a88ee599e795acff0080779ef88b04.png)

**Comment by xavdid** [comment]
@justin-lee-zapier thanks for the report! As it happens, the doc page you linked is stored in django admin. I'll open a slack thread with you to show you how to update.
