### ISSUE TITLE
Broken hyperlink

### ISSUE THREAD

**Issue by semenmiroshnichenko** [zapier/visual-builder#21]
**Link to documentation with issue**

https://platform.zapier.com/docs/oauth

**Describe the content issue**

In a sentence "If your OAuth 2 implementation supports refresh tokens you may optionally configure a “Refresh Token” request." the "request"-link is broken.

**What could be improved?**

Fix it ;-)

**Screenshots**

https://i.imgur.com/wAOAgT2.png

**Comment by maguay** [comment]
@semenmiroshnichenko Thank you, just got that fixed!
