### ISSUE TITLE
Migrate button stuck loading

### ISSUE THREAD

**Issue by chrisventura** [zapier/visual-builder#24]
**Describe the bug**

Cloned my current production integration, made a few small changes, tried to migrate users over to the new version, and the button to migrate gets stuck loading.

**To Reproduce**

List steps to reproduce the behavior:

1. Go to the **Version** page of my integration. 
2. Use the **Migrate** option in the dropdown for version 1.0.1.
3. Button should be loading forever.

**Expected behavior**

Expect the button to eventually stop loading so I could migrate my users.

**Screenshots**

![image](https://user-images.githubusercontent.com/4053234/57670839-ab5d9980-75d6-11e9-9526-dcb3c7cb54ff.png)

**Browser Info**

 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version:74.0.3729.131

**Additional context**

**Comment by maguay** [comment]
@chrisventura Sorry about that! This is a known issue our team is working to resolve! Feel free to reach out to support@zapier.com if you have any other issues.
