### ISSUE TITLE
Double text

### ISSUE THREAD

**Issue by semenmiroshnichenko** [zapier/visual-builder#26]
**Link to documentation with issue**

https://platform.zapier.com/partners/feature-requests-bugs

**Describe the content issue**

Double text "create new create new"

**What could be improved?**

Fix text

**Screenshots**

![image](https://user-images.githubusercontent.com/3511513/57754558-097da000-76ef-11e9-92b0-0768bdf88d10.png)

**Comment by maguay** [comment]
@semenmiroshnichenko Thank you for pointing that out, just got it fixed!
