### ISSUE TITLE
Looking for logs

### ISSUE THREAD

**Issue by tradingbills** [zapier/visual-builder#37]
We're looking for logs of users that have accessed our built triggers and actions. We'd like to see the usage and metrics of activity with our triggers and actions.

**Comment by matthewheath** [comment]
At present, the visual builder doesn't have a way to expose these reports to developers. That said, I've logged this with our developer platform team so they're aware of the level of interest in this feature.

For faster support in the future, I recommend using the contact form at https://zapier.com/app/contact-us and selecting the **Developing an app on the Zapier Platform** option so your request is routed to the right team.
