### ISSUE TITLE
How does connection label works

### ISSUE THREAD

**Issue by yomitomi** [zapier/visual-builder#38]
Hello!
I am creating a Zapier integration with the help of the Visual builder.
I wanted to use connnection label in order to distinguish between different authenticated accounts for the integration.
I'm using OAuth2 authentication flow.
The test API call is mage to /me endpoint which returns JSON of a form { "name":  "name", "metadata": "metadata",}

So, my expectation is if I put `{{bundle.inputData.name}}` into the Connection label field in the Visual builder, then anytime I'm adding new account and running the test API call on it, the label should be produced automatically based on the response.

However, expectations do not correspond to reality.
So, when I authenticate new account for the integration it just puts the bundle.inputData.name as a connection label and does not update it on the test API call.

Question: does my expection match reality and I'm doing something wrongly or vice versa?

Additional question: assuming I'm an end user, and the integration is configured to set connection label based on the result of test api call. When this test call will happen for the end user? During the setup of zap and testing section?

**Comment by matthewheath** [comment]
Hello there,

Thanks for writing this issue.

We have a guide to implementing and customising the connection label at https://platform.zapier.com/docs/auth#how-to-add-a-connection-label-to-authenticated-accounts.

If you need further help with this, please use the contact form at https://zapier.com/app/contact-us and select the **Developing an app on the Zapier Platform** option to get routed to the team that handles these queries.
