### ISSUE TITLE
Github endpoint specifications in trigger/action documentation returns a 404

### ISSUE THREAD

**Issue by AlexMathew** [zapier/visual-builder#4]
**Link to documentation with issue**

The issue is in the API configuration step of the trigger and action pages.
https://zapier.github.io/visual-builder/quickstart/build-trigger
https://zapier.github.io/visual-builder/quickstart/build-action

**Describe the content issue**

The Github API endpoint specified in the API configuration section of the documentation (and the included screenshot) does not match what is provided in the Github API documentation. Using what is currently specified returns a 404 on testing the request. Changing the endpoint to `https://api.github.com/repos/{{bundle.authData.username}}/{{bundle.inputData.repo}}/issues` works as expected. 

The Github API documentation does include this, which could be a possible explanation of what happened -

> Warning: The API may change without advance notice during the preview period. Preview features are not supported for production use. 

**Additional context**

Including relevant links from the Github API documentation - 
https://developer.github.com/v3/issues/#list-issues-for-a-repository
https://developer.github.com/v3/issues/#create-an-issue

**Comment by maguay** [comment]
@AlexMathew Thank you for pointing that out! Looks like you need to include the username of the repo owner (I think I may have been including that manually when testing), so to make sure this works with any repository the user has access to, I updated the trigger and action sections to both include a `username` field so users can specify both the repo and username they need: https://github.com/zapier/visual-builder/commit/c3e30b9f2d6b786ff5b85ff969374c6f1ce29099#diff-0a1bd9fa7ae2955eaa9612b26b026565

**Comment by AlexMathew** [comment]
Sounds great! Glad I could help!
