### ISSUE TITLE
Test Configuration is in documentation but not in Visual Builder

### ISSUE THREAD

**Issue by ansonkao** [zapier/visual-builder#44]
**Link to documentation with issue**

https://platform.zapier.com/docs/faq#how-do-i-define-rest-hooks-and-use-the-embedded-tester-with-them

**Describe the content issue**

Test Configuration is in documentation, see here:

![image](https://user-images.githubusercontent.com/300092/61160977-c31aa680-a4cf-11e9-8859-a55af625606f.png)

...but it is not in Visual Builder. This is what I see:

![image](https://user-images.githubusercontent.com/300092/61160999-de85b180-a4cf-11e9-946e-a29da2da8da3.png)

**Comment by matthewheath** [comment]
For the **Subscribe** function, `raw mode` isn't available unless you've specified input fields for that specific Trigger, it's only available for the **Unsubscribe** function as that will have input data from the **Subscribe** function automatically passed into it.

For quicker support in the future, it's worth using the contact form at https://zapier.com/app/contact-us and then selecting **Developing an app on the Zapier Platform** as that will get routed to the appropriate team for support with these sorts of questions.
