### ISSUE TITLE
CLI Docs have overlay issues in Firefox

### ISSUE THREAD

**Issue by kgodtfredsen** [zapier/visual-builder#47]
**Link to documentation with issue**

Pages like https://zapier.github.io/zapier-platform/#making-http-requests have layout issues in Firefox.

**Describe the content issue**

The headers are overlaying the text, screenshot here:

https://zappy.zapier.com/750D0310-45E6-4125-AC59-46CDE0A8CF74.png

**Comment by matthewheath** [comment]
Closing this as this isn't an issue on the new hosted docs: https://platform.zapier.com/cli_docs/docs#making-http-requests
