### ISSUE TITLE
Incorrect usage of the word "depreciation" and "depreciate"

### ISSUE THREAD

**Issue by JohnDMathis** [zapier/visual-builder#56]
**Link to documentation with issue**
https://platform.zapier.com/docs/versions

**Describe the content issue**

This article mixes usage of the words "deprecate", "deprecation" and "deprecated" with "depreciate" and "depreciation". Depreciate is a financial term, while Deprecate is a software term.

**What could be improved?**

The resolution is very simple: just remove the "i" from all uses of Depreciate, Depreciation, etc.

**Comment by matthewheath** [comment]
Thanks for spotting this! Fixed. 🙂
