### ISSUE TITLE
Planning guide copy has a couple typos

### ISSUE THREAD

**Issue by twalkr** [zapier/visual-builder#68]
**Link to documentation with issue**

https://platform.zapier.com/partners/planning-guide

**Describe the content issue**

-----

**How to Design Successful Zapier Integrations**

Existing copy:

>It starts with a Google search, perhaps, or a peek at Zapier's App Directory to find a new integration. Then the user makes a new Zap, either manually or from a Zap Template, and chooses your app. **They** they connect their account with your app, set up the

Suggested copy:

>It starts with a Google search, perhaps, or a peek at Zapier's App Directory to find a new integration. Then the user makes a new Zap, either manually or from a Zap Template, and chooses your app. **Then** they connect their account with your app, set up the

----

**Include workflow scenarios**, 

Existing:

>where some action inside your app triggers a Zap. In an email or chat app, a “New Starred Email” trigger lets users do something in your app to trigger**s** a Zap. This helps users build automated workflows that start with an action on their part.

Suggested:

>where some action inside your app triggers a Zap. In an email or chat app, a “New Starred Email” trigger lets users do something in your app to trigger a Zap. This helps users build automated workflows that start with an action on their part.

-----

**Actions**

>Triggers are focused on data **(that?)** has been added in your app.

![](https://zappy.zapier.com/59E19B56-FDBA-4DB0-ACDD-70E1B79C36FF.png)

>That will help you find other actions that may need **(to be?)** added.

![](https://zappy.zapier.com/9167BD46-EE76-4A35-98B4-7CADBA661EF2.png)

----

**Actions may create multiple items if needed**, 

Existing:

>using the same data, though you will likely need to customize the API call code to create both (multiple?) items at once. (mixing both and multiple)

Suggested:

>using the same data, though you will likely need to customize the API call code to create both items at once. Only do this for linked items, such as if an app stores customers and customer addresses separately. If the multiple objects (items?) that need to be created are top-level, complex objects (items?) in your app,  (mixing items and objects)

**Comment by matthewheath** [comment]
Fixed and merged.
