### ISSUE TITLE
Slack invitation link has been expired

### ISSUE THREAD

**Issue by pocke** [zapier/visual-builder#71]
**Link to documentation with issue**

https://platform.zapier.com/partners/faq#join-zapier-platform-slack

**Describe the content issue**

> Zapier’s Platform team has a community Slack channel dedicated to helping developers with new and existing app integrations. We’re a worldwide team, so there’s usually someone around to answer your questions. We’d love to hear your experience building on Zapier.

The slack invitation link has been expired. It is https://join.slack.com/t/zapier-platform/shared_invite/enQtNTg1MjM5NjMzNTI3LWVhZjk3NjFlNWFiMTBmMDExMzI5NDZiZmFiOTJjYmI3NmY2MzEwZDUxNzQ3MTliMTM5N2M3NGM2MmQ2Y2VkODE.

**What could be improved?**

I guess you can re-create an invitation URL, and update it.

**Screenshots**

![191016154007](https://user-images.githubusercontent.com/4361134/66894404-44338d80-f02b-11e9-971a-670223aadc1d.png)

**Additional context**

nothing

**Comment by xavdid** [comment]
this has been updated, thank you!
