### ISSUE TITLE
Question about Enabling Early Access

### ISSUE THREAD

**Issue by eelumir** [zapier/visual-builder#75]
Hello!

We are just about to Make our App public, but I have a question about what happens. 

Will all the older versions be there still, so other can still use the old version?

Or will older users be automatically moved to the new version?

Thank you!

**Comment by matthewheath** [comment]
Hello there,

Just to be clear up front, we don't typically use these issues for support — the best thing to do is to write to us through the contact form (https://zapier.com/app/contact-us) and select the **Developing an app on the Zapier Platform** option so it gets routed to the correct team.

In this case, the older versions will still be there — users will not automatically be migrated: you'll need to manually migrate them following the guide at https://platform.zapier.com/docs/versions#migrate-users-to-your-new-integration-version.
