### ISSUE TITLE
Design an Input Field Form (Key and Label Swapped)

### ISSUE THREAD

**Issue by bdelanghe** [zapier/visual-builder#8]
**Link to documentation with issue**

https://zapier.github.io/visual-builder/quickstart/build-trigger

**Describe the content issue**

The Screenshot of the form editor has 'Label' before 'Key. Currently the form has 'Key' preceding 'Label'. 

**What could be improved?**

The image should be replaced with an updated screenshot to avoid confusion.

**Screenshots**

Help Doc:
![disign an input field form](https://user-images.githubusercontent.com/1240090/53604448-8c786b00-3b82-11e9-9e09-ab8247b82778.png)

Current Layout:
<img width="899" alt="screenshot 2019-02-28 17 54 37" src="https://user-images.githubusercontent.com/1240090/53604502-afa31a80-3b82-11e9-92d2-3357dbcbe9cc.png">

**Additional context**

Image is after heading "2. Design an Input Field Form"

**Comment by maguay** [comment]
@bdelanghe Thanks for pointing that out! Our Input Designer was actually showing slightly different design and help text in Triggers and Actions before, so we've now updated that to have the field name show first in both editors, and have updated the docs to reflect the changes. Thanks for pointing it out!
