### ISSUE TITLE
Is there a way to show an error to client when Zapier action fails?

### ISSUE THREAD

**Issue by khurana3192** [zapier/visual-builder#80]
Lets assume our API for an action was expecting some data that user didn't provide correctly. We send a status 400 along with the message. However, to the client they only see this

"Got 400 while calling https://ourdomain.com/ourapi/ourendpoint"

Is there a way we can send an error message so that client is aware about what exactly they are doing wrong?

**Comment by xavdid** [comment]
@khurana3192 The best way to do that is to explicitly throw an error object, like `throw new Error('some message here')`. There's docs on this [here](https://github.com/zapier/zapier-platform/tree/master/packages/cli#error-handling).

**Comment by khurana3192** [comment]
Hey @xavdid ,

Thanks for getting back on this one.

Unfortunately, my APIs are using PHP (the APIs that get called for my actions and triggers), and throw new Exception('error message') is not helping in this case.

Can't we send a JSON payload along with HTTP code?
If yes, what should be the format of that JSON?

**Comment by xavdid** [comment]
You can't throw the json directly, but you can send along data from that response as the message. something like `throw new Error(response.json.errors[0])`. To do that, make sure you're not throwing immediately when a non-successful response comes back (namely, don't call `response.throwForStatus()`).

Does that make sense? If not, could you post a snippet of your request code?

**Comment by khurana3192** [comment]
Hey @xavdid,

Thanks for getting back.

I think you are referring to a backend environment which runs on node.js. Our APIs (which we have plugged with Zapier) are running PHP.

We throw response code like this:
```
http_response_code(400);
$status = "fail";
$message = "Offset not allowed more than a week";
$array = array("status"=>$status,"message"=>$message);
$json = json_encode($array);
echo $json;
exit;
```
And the same error message is not presented to users when our API fails due to any value or misconfiguration

**Comment by khurana3192** [comment]
I figured this out @xavdid. I never thought I had to this in the code view inside API configurator.
