### ISSUE TITLE
typo for Authenticstion at https://platform.zapier.com/quickstart/auth

### ISSUE THREAD

**Issue by hakanson** [zapier/visual-builder#82]
https://platform.zapier.com/quickstart/auth

**Describe the content issue**
Near the end of section 1, Authentication is misspelled as "Authenticstion"

> Click the Authenticstion tab in Zapier visual builder

**What could be improved?**

fix typo

**Screenshots**

n/a

**Additional context**

n/a

**Comment by xavdid** [comment]
thank you! Fixed in a5e95f56711afeca7dfae868207c955cce4839c0
