### ISSUE TITLE
Scrolling issue with the new interface

### ISSUE THREAD

**Issue by Post79** [zapier/visual-builder#92]
**Describe the bug**

While building Zaps in the new interface I noticed we need to scroll a lot. Every time I close/finalise a step, the screen position far from ideal. Especially when building and testing zaps all day (Zapier Expert).

**To Reproduce**

While working in a Zap:

1. Edit a zap step
2. After clicking "Done", the current step collapses.
3. The screen scrolls down way too far

Now two things can happen:

- When editing an **existing Zap**, the current view now suddenly scrolls 2, 3 or 4 steps further down the zap. I need to scroll back up and retrace my position.
- When building a **new Zap**, the current view goes to the bottom of the page. However the next move is to add a step or open an existing step again. Now I have to scroll down with every click to get my new fields back in view. This is a quite a few times while building a step. Especially with dropdown lists this is frustrating as the open up outside of view.

**Expected behavior**

When closing an action/step, I expect the next field/button/whatever I need to work on is at the top of my screen.
When opening/adding a step detail panel, I expect the first fields at the top of my screen. This now happens only while opening a step (first click), but not on the step details or add new step actions.

Every time I finalise a part of my zap or editing or adding something new, I expect that to fill my screen and be at the top of my screen. 

**Screenshots**

When selecting a current step, it scrolls up to the top nicely. When opening a step detail it does not (not fully):
https://cl.ly/95612e6f12c0

When closing a step when done, I end up a few steps down the line (depends on the height of the step box):
https://cl.ly/b58bedc8c627

**Browser Info**

 - OS: macOS Mojave
 - Browser: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit) (but also on Safari)

**Additional context**

For the new step part of the problem it would be a fix to bottom padding to the bottom of the builder UI equal to the browser height.

There might be some other moments while building/editting/debugging zaps when scrolling the current field to the top of the screen would speed up my workflow. These are just a few big ones.

**Comment by xavdid** [comment]
Hi there! We appreciate the feedback here. I've routed it to the right team and it's been appropriately logged. 

It's worth noting that this repo only fields issues for our developer documentation and other developer tools. In the future, general Zapier product feedback (like for the editor) is best submitted to our support team. They're reachable at https://zapier.com/contact-us.

Thanks!
